name: page_object
description: A Flutter package to help with implementing the Page Object pattern in a Flutter app..
version: 0.2.0
homepage: https://github.com/eBay/flutter_glove_box/
repository: https://github.com/eBay/flutter_glove_box/tree/master/packages/page_object
issue_tracker: https://github.com/eBay/flutter_glove_box/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
