name: page_object_fol_edition
description: A Flutter package to help with implementing the Page Object pattern in a Flutter app.
version: 0.3.0
homepage: https://github.com/fatherOfLegends/page_object
repository: https://github.com/fatherOfLegends/page_object
issue_tracker: https://github.com/fatherOfLegends/page_object/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
